Multi servers
innogames/grafsy pull request #1
Opened 2019-04-29 12:40 UTC by Felixoid

Here is a multiserver implementation as well as:

- Using innogames/grafsy
- Restructuring of package
- Race read/write mitigation
- Other small changes

2019-05-06 11:23 UTC, Woellchen requested changes
actually at some point i stopped taking detailed looks because the code is very hard to read and understand
for this first round of the review lets please try to simplify the code. i am especially talking about the new code for now.
there are way too many fors in ifs in fors and so on. lets try to reduce the complexity first
instead of adding more and more indentions please extract logic into smaller functions and reuse them if possible
then we can try to unify some logic and get rid of similar code
when those basics are done we can have another look at details and best practices :)

2019-05-06 11:23 UTC, Woellchen commented on client.go
> +	monChannels map[string](chan string)
redundant parantheses

2019-05-06 11:23 UTC, Woellchen commented on client.go
> +	mainChannels map[string](chan string)
redundant parantheses

2019-05-06 11:23 UTC, Woellchen commented on client.go
> +var chan_lock sync.Mutex
please no underscore in go

2019-05-06 11:23 UTC, Woellchen commented on client.go
> +	/*
meh. in go you usually use `//` comments only

2019-05-06 11:23 UTC, Woellchen commented on client.go
> +	}
`defer f.Close()` is safer than `f.Close()`

2019-05-06 11:23 UTC, Woellchen commented on client.go
> +//  1)
broken comment?

2019-05-06 12:58 UTC, Felixoid commented on client.go
> +var chan_lock sync.Mutex
done everywhere

2019-05-06 12:59 UTC, Felixoid commented on client.go
> +	/*
Was there before, but fixed

2019-05-06 12:59 UTC, Felixoid commented on client.go
> +	}
done

2019-05-06 15:04 UTC, Woellchen requested changes

2019-05-06 15:04 UTC, Woellchen commented on monitoring.go
> +func (m *Monitoring) Increase(metric *int, value int) {
i am very unhappy with this. lets not use pointers if we dont really need them
better would be three methods: `IncreaseSaved`, `IncreaseSent`, `IncreaseDropped`. and they could receive just the backend identifier and the delta

2019-05-06 15:04 UTC, Woellchen commented on monitoring.go
> +func (m *Monitoring) Increase(metric *int, value int) {
later we have to restructure this anyways. then we could use `atomic` package

2019-05-06 15:04 UTC, Woellchen commented on monitoring.go
> +		m.clean()
the problem here is that we might lose data because the `statLock` lock is acquired and released for every iteration in the loop above and then again in the `clean` function. there is plenty of time where concurrent goroutines could increase the counters
it would be better to remove the locking from inside the `clean` function and instead lock around the backends including `clean`. it is anyways a better idea to do the locking in a higher level place

2019-05-06 16:28 UTC, Felixoid commented on monitoring.go
> +func (m *Monitoring) Increase(metric *int, value int) {
We'll leave it until next version

2019-05-06 16:28 UTC, Felixoid commented on monitoring.go
> +		m.clean()
done

2019-05-06 17:00 UTC, Felixoid commented on client.go
> +						c.Mon.Increase(&c.Mon.got.retry, 1)
This is an error, it should be `c.Mon.stat[backend].retry`. Doesn't make a lot of sense, TBH.  
Maybe, we could rename it to `from_retry` and then put to the `stat` map

2019-05-07 11:14 UTC, Woellchen requested changes

2019-05-07 11:14 UTC, Woellchen commented on client.go
> +	//
argh. no empty lines please :D

2019-05-07 11:14 UTC, Woellchen commented on config.go
>  	// There are 3 metrics per backend
does the comment still match now? i think it should be different now

2019-05-07 11:55 UTC, Woellchen approved these changes

2019-05-07 13:46 UTC, merged